//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PAYMENT_DATA_RECURRENT> PAYMENT_DATA_RECURRENT { get; set; }
        public virtual DbSet<PAYMENT_DATA_SINGLE> PAYMENT_DATA_SINGLE { get; set; }
        public virtual DbSet<PAYMENT_GROUP> PAYMENT_GROUP { get; set; }
        public virtual DbSet<PAYMENT_TYPE> PAYMENT_TYPE { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_ROLE_PAYMENT_GROUP> USER_ROLE_PAYMENT_GROUP { get; set; }
    }
}
