//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PAYMENT_DATA_RECURRENT> PAYMENT_DATA_RECURRENT { get; set; }
        public DbSet<PAYMENT_GROUP> PAYMENT_GROUP { get; set; }
        public DbSet<PAYMENT_TYPE> PAYMENT_TYPE { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<USER_ROLE_PAYMENT_GROUP> USER_ROLE_PAYMENT_GROUP { get; set; }
        public DbSet<PAYMENT_DATA_SINGLE> PAYMENT_DATA_SINGLE { get; set; }
    }
}
