//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Data
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class PAYMENT_TYPE
    {
        public PAYMENT_TYPE()
        {
            this.PAYMENT_DATA_RECURRENT = new HashSet<PAYMENT_DATA_RECURRENT>();
            this.PAYMENT_DATA_SINGLE = new HashSet<PAYMENT_DATA_SINGLE>();
        }
    
        public int PAYMENT_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<PAYMENT_DATA_RECURRENT> PAYMENT_DATA_RECURRENT { get; set; }
        public virtual ICollection<PAYMENT_DATA_SINGLE> PAYMENT_DATA_SINGLE { get; set; }
    }
}
