//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO.Data
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class ROLE
    {
        public ROLE()
        {
            this.ROLE1 = new HashSet<ROLE>();
            this.USER_ROLE_PAYMENT_GROUP = new HashSet<USER_ROLE_PAYMENT_GROUP>();
        }
    
        public int ROLE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> REPORTING_TO { get; set; }
        public Nullable<int> ROLE_ACTIVITY_ENUM { get; set; }
    
        public virtual ICollection<ROLE> ROLE1 { get; set; }
        public virtual ROLE ROLE2 { get; set; }
        public virtual ICollection<USER_ROLE_PAYMENT_GROUP> USER_ROLE_PAYMENT_GROUP { get; set; }
    }
}
